name: Optuna CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
#        python-version: [2.7, 3.5, 3.6, 3.7]
        python-version: [3.5, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools
        python setup.py sdist
        pip install --progress-bar off $(ls dist/*.tar.gz)

    - name: Check minimal import
      run: |
        python -c 'import optuna'

    - name: Install testing dependencies
      run: |
        pip install --progress-bar off $(ls dist/*.tar.gz)[testing]

    - name: Run unit tests
      env:
        OMP_NUM_THREADS: 1
      run: |
        pytest tests

    - name: Run ChainerMN unit tests
      env:
        OMP_NUM_THREADS: 1
      run: |
        mpirun -n 2 -- pytest tests/integration_tests/test_chainermn.py
